---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: sh -x ./.gitpod/setup.sh
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

workspaceLocation: "./redmine"

vscode:
  extensions:
    - bung87.rails
    - rebornix.ruby
